### ISSUE TITLE
Package unusable

### ISSUE THREAD

**Issue by fregante** [kenchris/urlpattern-polyfill#85]
There are several issues with versions past v1:

- [x] index.cts does not export URLPattern
- [ ] index.cts does not match the types (which say it exports URLPattern), so TS passes but it fails at runtime
- [x] url-patterns.cts is not importable in recent Node versions because it's not specified in the `exports` map
- [x] url-patterns.cts is not importable in TypeScript because there's no `url-patterns.d.ts`
- [ ] using `import {URLPattern} from "urlpattern-polyfill"` **also** polyfills the global, which is not what one expects
- [x] using `import "urlpattern-polyfill"` as a polyfill is not usable in TypeScript because the `URLPattern` is not defined globally

**Comment by fregante** [comment]
Generally I'd advise:

- Drop the ESM version, it offers no advantage here. Both bundlers and node can already `import` CJS files
	- Alternatively, drop the CJS version: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- Drop `exports` map because it's going to cause more issues than it's worth (given the list above)

**Comment by kenchris** [comment]
Not everyone uses bundlers

**Comment by kenchris** [comment]
Maybe you could write tests for some of these?

**Comment by fregante** [comment]
> Not everyone uses bundlers

None of these are related to bundlers. They're usability issues. Most are typescript-related, but some are plain Node too. Try importing or requiring url-pattern.cts directly on Node 12.7.0 or later.

**Comment by kenchris** [comment]
It was a comment related to the "drop the ESM version" comment

**Comment by kenchris** [comment]
You are right about the declare global, and the below works. We need to add tests for that

```ts
export {};

declare global {
 type URLPatternInput = URLPatternInit | string;

  class URLPattern {
    constructor(init?: URLPatternInput, baseURL?: string);

    test(input?: URLPatternInput, baseURL?: string): boolean;

    exec(input?: URLPatternInput, baseURL?: string): URLPatternResult | null;

    readonly protocol: string;
    readonly username: string;
    readonly password: string;
    readonly hostname: string;
    readonly port: string;
    readonly pathname: string;
    readonly search: string;
    readonly hash: string;
  }

  interface URLPatternInit {
    baseURL?: string;
    username?: string;
    password?: string;
    protocol?: string;
    hostname?: string;
    port?: string;
    pathname?: string;
    search?: string;
    hash?: string;
  }
  
  interface URLPatternResult {
    inputs: [URLPatternInput];
    protocol: URLPatternComponentResult;
    username: URLPatternComponentResult;
    password: URLPatternComponentResult;
    hostname: URLPatternComponentResult;
    port: URLPatternComponentResult;
    pathname: URLPatternComponentResult;
    search: URLPatternComponentResult;
    hash: URLPatternComponentResult;
  }
  
  interface URLPatternComponentResult {
    input: string;
    groups: {
        [key: string]: string | undefined;
    };
  }
}
```

**Comment by fregante** [comment]
> It was a comment related to the "drop the ESM version" comment

I'm not sure how that's related to bundlers or no bundlers either. The ESM file can't be loaded in the browser because it imports a CJS file; it's just a mask, but it does nothing that Node, bundlers or browsers can't already do.

**Comment by SanderElias** [comment]
@fregante It doesn't import a CJS file. It is a proper ESM module that is fully self-contained.
The following HTML works for me without an issue:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test document for browser testing</title>
</head>
<body>
  <script type="module">
    import {URLPattern} from 'https://cdn.jsdelivr.net/npm/urlpattern-polyfill@4.0.1/dist/index.js';
    const header = document.createElement('h1');
    header.textContent = 'Failed testing document for URL pattern testing';
    if (typeof URLPattern === 'function') {
      header.textContent = 'Succeeded testing document for URL pattern testing';      
    }
    document.body.appendChild(header);
  </script>  
</body>
</html>
```

**Comment by fregante** [comment]
> It doesn't import a CJS file

Oh, I saw that `index.cjs` was shipped as is so I assumed the .js version was too. 👍 

My initial suggestion still applies though, because the code you wrote doesn't actually require ESM since it also sets the global:

```diff
- import {URLPattern} from 'https://cdn.jsdelivr.net/npm/urlpattern-polyfill@4.0.1/dist/index.js';
+ import 'https://cdn.jsdelivr.net/npm/urlpattern-polyfill@4.0.1/dist/index.js';
```

The polyfill only needs to be self-contained, it doesn't need to use any specific module format.

**Comment by SanderElias** [comment]
As a responsible polyfill, it only sets the global _when it's undefined_ 
You can check in chrome 100, which has a native implementation too.
And sadly, we need two different versions. Current tooling isn't able to handle it properly. I tried. 
I would love to be able to distribute ESM only and be done with it. 
Sadly, a load of tools, bundlers, and devs still require CommonJs.

**Comment by SanderElias** [comment]
@fregante We just merged a couple of small upgrades. I suspect a new version will be pushed to NPM a little bit later.
Can you check if it marks off all of your issues?

**Comment by fregante** [comment]
> As a responsible polyfill, it only sets the global when it's undefined

I'm not saying otherwise, I'm just saying that if I import a specific variable I don't expect it to also change the global state. 

I must also add that your last demo never uses the native implementation, so presumably it's not the suggested way of using it. 

> And sadly, we need two different versions. Current tooling isn't able to handle it properly. I tried.

Fair, this is why I suggested dropping the ESM version first and just leave a module-less (export-less) polyfill file and a CJS file with export. This fits all node versions, all bundlers, and all polyfill-only browsers (browsers already *always* get the polyfill currently)

**Comment by fregante** [comment]
To recap:


- polyfill.js (no exports)
- index.js (CJS)
- polyfill.d.ts that sets the global type
- index.d.ts that exports the types normally

Then in package.json:
- no `exports` map
- no `type=module`
- no `module` field 

Allowed usages:

```js
import "urlpattern-polyfill/polyfill" // browser, bundlers and node
import {URLPattern} from "urlpattern-polyfill" // bundlers and node
require("urlpattern-polyfill/polyfill") // bundlers and node
const {URLPattern} = require("urlpattern-polyfill") // bundlers and node
``` 

The only broken usage is:

```js
❌ import {URLPattern} from "full https url://urlpattern-polyfill" // no browser support
``` 
But I don’t think that's worth your time and its current support is misleading (because it's still acting as a polyfill so the specific import is not needed)

**Comment by SanderElias** [comment]
> I'm not saying otherwise, I'm just saying that if I import a specific variable I don't expect it to also change the global state.

I get what you are saying. However, common sense dictates that you should cater to the majority. In this case, the majority will expect that the polyfill does put URLPattern on the global state. 
Most devs are not going to import the implementation to do something with it. However, we do recognize there might b a use-case for that. 

I also get what you express in your last msg. But that is currently not possible to produce with the tooling (and available time) we have.
If you can set up a tool chain that compiles the TS into the files you propose, We are all ears, and would welcome an PR.

**Comment by fregante** [comment]
> Can you check if it marks off all of your issues?

~~Please review them one by one because I'd just be repeating myself. I made my case. I checked one point and it's still missing because of the (unnecessary) exports map.~~ _Edit: I checked them, only one is left_

I get what you're saying but setting a polyfill when I import a variable ***is not*** responsible. 

I outlined several better (and very feasible) solutions so I can't do anything else.

**Comment by fregante** [comment]
> If you can set up a tool chain that compiles the TS into the files you propose

I could, but it doesn't look like the suggested solution is welcome, so I can't submit a PR.
